extends Node

@onready var Text = [
	"fantastic",
	"spiffing",
	"tubular",
	"whimsical",
	"serendipitous",
	"tantalising",
	"effervescent",
	"quintessential",
	"floundering",
	"bodacious",
	"xenosaga",
	"monstrous",
	"clinical",
	"rhabdophobia",
	"anthropomorphism",
	"compatibility",
	"commitment",
	"preserved",
	"harmonious",
	"characterised",
	"moonscorched",
	"lollygagging",
	"inspection",
	"colossus",
	"naturalisation",
	"nonflammable",
	"senselessness",
	"firmament",
	"zarathustra",
	"magnificent",
	"lookbehindyoutheresascaryghost"
]
